### ISSUE TITLE
Mudar de Json para Yaml

### ISSUE THREAD

**Issue by limadaniel70** [limadaniel70/AutoGroup#18]
Este é um exemplo com json:

```json
{
    "equipe 1": [
        "Vivian Rodgers",
        "April Whitehead",
        "Pete Anthony",
        "Silvia Simms",
        "Katy McFarland",
        "Lucille Steele"
    ],
    "equipe 2": [
        "Pat Hahn",
        "Jorge Hester",
        "Taylor Delaney",
        "Darryl Ogden",
        "Nathan Shaw",
        "Dianne Shields"
    ],
    "equipe 3": [
        "Brandy Brennan",
        "Betty Blackburn",
        "Candy Shea",
        "Kenny Ewing",
        "Sally Knapp",
        "Cameron Mills"
    ]
}
```

E este é um exemplo com yaml:
```yaml
equipe 1:
  - Vivian Rodgers
  - April Whitehead
  - Pete Anthony
  - Silvia Simms
  - Katy McFarland
  - Lucille Steele

equipe 2:
  - Pat Hahn
  - Jorge Hester
  - Taylor Delaney
  - Darryl Ogden
  - Nathan Shaw
  - Dianne Shields

equipe 3:
  - Brandy Brennan
  - Betty Blackburn
  - Candy Shea
  - Kenny Ewing
  - Sally Knapp
  - Cameron Mills
```

Yaml vai tornar muito mais fácil de entender.
